server:
  port: 8082
spring:
  application:
    name: j-cloud-consumer-feign

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
